# -*- coding: utf-8 -*-
"""A108260050-施振宇-Week12 -更正版

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s6iBe1gW1KXjd_hgk3STXIOZmciMX3A6
"""

n=0     #初始條件
result=0

while n < 10:  #判斷條件
    n=n+1   #更新條件
    result=result+n # 累加
print("finished")

n=0     #初始條件

while n < 10:  #判斷條件
    n=n+1   #更新條件
    if n==4:
     break #跳離迴圈
print("finished")

n=0     #初始條件

while n < 10:  #判斷條件
    n=n+1   #更新條件
    if n==4:
     continue #跳離迴圈+此次迴圈不執行
print("finished")

x=5
while True
    print("hello")
    x = x+1

#無窮迴圈:while True + break
while True
    print("Hello")
    if 條件:
        執行動作
    else:
        break

#請寫一個程式模擬密碼登入，使用者輸入密碼
#若密碼一致，則輸出「密碼正確」，否則輸出「登入失敗」

while True:
    password = input("Enter Your Password")
    if password=="answer":
      print("Correct")
      break
    else:
        print("Fail,Try Again")

#請寫一個程式模擬帳號與密碼登入，使用者輸入密碼
#若密碼一致，則輸出「帳號與密碼正確」，否則輸出「登入失敗」

while True:
    account = input("Enter Your Account")
    password = input("Enter Your Password")
    if account=="answer":
      print("Correct")
      break
    else:
        print("Fail,Try Again")
    if password=="answer":
      print("Correct")
      break
    else:
        print("Fail,Try Again")

password="chowchole"
times=0

while times <=3:
    answer = input("Enter Your Password: ")
    if answer == password:
        print("登入成功")
        break
    else:
        times = times+1
        chance = 3-times
        print("密碼錯誤!還有",chance,"次機會")

for a in range(6):
    print(a,end=" ")

sum=0

for x in range(1,11,2):
    sum = sum + x

print("1+3+5+7+9=",sum)

n = int(input('請輸入n值?'))
sum = 0
for i in range(1,n+1):
    sum = sum +i*i;
print(sum)

