# -*- coding: utf-8 -*-
"""Copy of Week7-A108260050-施振宇.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x7ogV-IwvK2SZ8EeJ4bKniFnx6eWd7Wk
"""

player="Ron Harper"
player_list=["Ron Harper","Michael Jordan","Scottie Pippen","Dennis Rodman","Luc Longley"]
player_tuple=tuple(player_list)
player_dict={
    "PG":"Ron Harper",
    "SG":"Michael Jordan",
    "SF":"Scottie Pippen",
    "PF":"Dennis Rodman",
    "C":"Luc Longley"
}
player_set=set(player_list)

print(type(player))
print(type(player_list))
print(type(player_tuple))
print(type(player_dict))
print(type(player_set))

s1='春眠不覺曉，處處聞啼鳥。'
print(s1)

s2="夜來風雨聲，花落知多少。"
print(s2)

s3='作者"孟浩然"詩名"春曉"'
print(s3)
s4="作者'孟浩然'詩名'春曉'"
print(s4)

s5='''   春眠不覺曉，處處聞啼鳥。
   夜來風雨聲，花落知多少。
   作者"孟浩然"詩名"春曉"
'''
print(s5)

s1="123"
s2="456"

s3=s1+s2
print(s3)

s4=s1*2
print(s4)

s5='春眠不覺曉，處處聞啼鳥。\n\
夜來風雨聲，花落知多少。\n\
\t作者"孟浩然" 詩名"春曉"'
print(s5)

s='0123456789'
print(s[0])
print('s[1]=',s[1])
print(s[-1])
print('s[-2]=',s[-2])

s='0123456789'

print('s=',s,'s[:]=',s[:])
print('s=',s,'s[5:]=',s[5:])
print('s=',s,'s[-2]=',s[-2:])
print('s=',s,'s[:5]=',s[:5])
print('s=',s,'s[:-2]=',s[:-2])

print('s=',s,'s[7:9]=',s[7:9])
print('s=',s,'s[-4:-1]=',s[-4:-1])
print('s=',s,'s[5:-2]=',s[5:-2])
print('s=',s,'s[2:10:2]=',s[2:10:2])
print('s=',s,'s[::-1]=',s[::-1])
print('s=',s,'s[-1::-1]=',s[-1::-1])

s='春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。'
print(len(s))

s='春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。'
list1=s.split(',')
print(list1)

list1=['春眠不覺曉','處處聞啼鳥','夜來風雨聲','花落知多少。']
s2='，'.join(list1)
print(s2)

s1='春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。'
print(s1.find('花落'))

s1='春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。'
print(s1.count('處'))

s1='春眠不覺曉，處處聞啼鳥，夜來風雨聲，花落知多少。'
s3=s1.replace('春','冬')
print(s3)

s1='An apple a day.'
print(s1.capitalize())

s1='An apple a day.'
print(s1.title())

s1='An apple a day.'
print(s1.swapcase())

s1='An apple a day.'
print(s1.upper())

s1='An apple a day.'
print(s1.lower())

t1=()
print(t1)

t2=('z', )
print(t2)

t3=(1,2,3)
print(t3)

t4=(1,2,3,4)
t5=(t4,5,6)
print(t5)

list1=[1,2,3,4]
t6=tuple(list1)
print(t6)

t1=(1,2,3,4)
t2=(5,6,t2)

print(len(t2))
print(t2[0])
print(t2[2][0])

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
print('購物清單shoplist為')
print(shoplist)

listm=[1,2.0,'Python']
print("串列可以包含各種資料型別的元素")
print(listm)

tuple2=('a', 'b', 1, 2)
list2=list(tuple2)
print(list2)

shoplist1=['牛奶','蛋','咖啡豆']
shoplist2=['西瓜','鳳梨']
shoplist_all=shoplist1+shoplist2
print(shoplist_all)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
print('顯示shoplist[0]為',shoplist[0])

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
index=shoplist.index('咖啡豆')
print("執行index=shoplist.index('咖啡豆')後")
print('index=',index)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist[1]='皮蛋'
print("執行shoplist='皮蛋'後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']

a=list('abcdefghijk')
print('a[:]為',a[:])
print('a[:5]為',a[:5])
print('a[5:]為',a[5:])
print('a[:-5]為',a[:-5])
print('a[-5:]為',a[-5:])

print('a[0:4]為',a[0:4])
print('a[-5:-3]為',a[-5:-3])

print('a[1:10:3]為',a[1:10:3])
print('a[-1:-4:-1]為',a[-1:-4:-1])
print('a[::-1]為',a[::-1])

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
print('購物清單shoplist的長度為',len(shoplist))

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.append('麵包')
print("執行shoplist.append('麵包')後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.insert(4,'蘋果')
print("執行shoplist.insert(4,'蘋果)後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.remove('蛋')
print("執行shoplist.remove('蛋')後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.pop(0)
print("執行shoplist.pop(0)後")
print(shoplist)

shoplist.pop()
print("執行shoplist.pop()後")
print(shoplist)

shoplist.pop(-1)
print("執行shoplist.pop(-1)後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
del shoplist[0]
print("執行 del shoplist[0]後")
print(shoplist)

shoplist=['牛奶','蛋','咖啡豆','西瓜','鳳梨']
shoplist.sort()
print("執行shoplist.sort()後")
print(shoplist)

shoplist=['milk','egg','coffee','watermelon']
shoplist.sort()
print("執行shoplist.sort()後")
print(shoplist)

shoplist.sort(reverse=True)
print("執行shoplist.sort(reverse=True)後")
print(shoplist)

list1=[1,2,3,4]
list2=list1
print('list1=',list1)
print('list2=',list2)

list1[2]=19
print('list1=',list1)
print('list2=',list2)

list2[2]=18
print('list1=',list1)
print('list2=',list2)

list1=[1,2,3,4]
list4=list1.copy()
print('list1=',list1)
print('list4=',list4)

list4[2]=19
print('list1=',list1)
print('list4=',list4)

season="1995-1996"
team="Chicago Bulls"
coach="Phill Jackson"
won_championship=True

records=[72,10]
starting_lineup=["Ron Harper","Michael Jordan","Scottie Pippen","Dennis Rodman","Luc Longley"]

best_chicago_bulls=[season,team,coach,won_championship,records,starting_lineup]
print(best_chicago_bulls)
print(type(best_chicago_bulls))
print(len(best_chicago_bulls))

print(best_chicago_bulls[0])
print(best_chicago_bulls[1])
print(best_chicago_bulls[2])
print(best_chicago_bulls[3])
print(best_chicago_bulls[4])
print(best_chicago_bulls[5])

print(best_chicago_bulls[-1])
print(best_chicago_bulls[-2])
print(best_chicago_bulls[-3])
print(best_chicago_bulls[-4])
print(best_chicago_bulls[-5])
print(best_chicago_bulls[-6])

print(best_chicago_bulls[0:3])
print(best_chicago_bulls[::2])
print(best_chicago_bulls[::-1])

best_chicago_bulls[5].append("Toni Kukoc")
print(best_chicago_bulls[5])

best_chicago_bulls[5].insert(6,"Toni Kukoc")
print(best_chicago_bulls[5])

center=best_chicago_bulls[5].pop()
print(center)
print(best_chicago_bulls[5])

best_chicago_bulls=[season,team,coach,won_championship,records,starting_lineup]
del best_chicago_bulls[5][0]
print(best_chicago_bulls[5])

best_chicago_bulls=[season,team,coach,won_championship,records,starting_lineup]

best_chicago_bulls[4].sort()
print(best_chicago_bulls[4])
best_chicago_bulls[4].sort(reverse=True)
print(best_chicago_bulls[4])
best_chicago_bulls[5].sort()
print(best_chicago_bulls[5])
best_chicago_bulls[5].sort(reverse=True)
print(best_chicago_bulls[5])

dict1={}
print(dict1)

lang={'早安':'Good Morning','你好':'Hello'}
print(lang)

a=[['早安','Good Morning'],['你好','Hello']]
dict1=dict(a)
print(dict1)

b=[('早安','Gooding Morning'),('你好','Hello')]
dict2=dict(b)
print(dict2)

c=(['早安','Gooding Morning'],['你好','Hello'])
dict3=dict(c)
print(dict3)

d=(('早安','Gooding Morning'),('你好','Hello'))
dict4=dict(d)
print(dict4)

lang={'早安':'Good Morning','你好':'Hello'}
print('「你好」的英文為',lang['你好'])

print('「你好嗎」的英文為',lang['你好嗎'])

lang={'早安':'Good Morning','你好':'Hello'}

lang['你好']='Hi'
print(lang)

lang['學生']='Student'
print(lang)

lang={'早安':'Good Morning','你好':'Hello'}
del lang['早安']
print(lang)

lang1={'你好':'Hello'}
lang2={'學生':'Student'}

lang1.update(lang2)
print(lang1)

lang1={'早安':'Good Morning','你好':'Hello'}
lang2=lang1
lang2['你好']='Hi'

print('lang1為',lang1)
print('lang2為',lang2)

lang1={'早安':'Good Morning','你好':'Hello'}
lang3=lang1.copy()
lang3['你好']='Hi'

print('lang1為',lang1)
print('lang3為',lang3)

s={1,2,3,4}
print(s)

s=set(('a',1,'b',2))
print(s)

s=set(['apple','banana','apple'])
print(s)

s=set({'早安':'Good Morning','你好':'Hello'})
print(s)

s=set('racecar')
print(s)

s=set('tiger')
print(s)

s.add('z')
print(s)

s.remove('t')
print(s)

a=set('tiger')
b=set('bear')
print(a)
print(b)

print(a|b)
print(a&b)
print(a-b)

a=set('tiger')
b=set('tigers')
print(a<=b)

a=set('tiger')
b=set('tigers')
print(a<b)

