# -*- coding: utf-8 -*-
"""Week5-A108260050-施振宇.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/122YLIY1qUoGmYQcwOXdJ49f7iW9e6xLp
"""

print("Hours")

print("123%60")

y=input("請問年紀?")
print("原來你",y,"歲")

y=int(input("請問年紀?"))
print("原來你",y,"歲")

name=input("請問貴姓大名?")
print("你好",name)

w=float(input("請問體重?"))
print("體重為",w)

上衣=int(input("請輸出上衣數量?"))
褲子=int(input("請輸入褲子數量?"))
背心=int(input("請輸入背心數量?"))

總金額=上衣*300+褲子*350+背心*400
print("訂購服裝的總金額為",總金額)

半徑=float(input("請輸入半徑?"))

PI=3.14159

圓周長=2*PI*半徑
圓面積=半徑*半徑*PI

print("圓周長為",圓周長,"圓面積為",圓面積)

c=float(input("請輸入攝氏溫度?"))
f=c*9/5+32
print("華氏溫度為",f
     )

money=int(input("請輸入本金"))
interest=float(input("請輸入年利率(%)?"))

y1=money*(1+interest/100)
y2=money*((1+interest/100)**2)
y3=money*((1+interest/100)**3)

print("第一年本利合為",y1)
print("第二年本利合為",y2)
print("第三年本利合為",y3)

第一次=int(input("請輸入第一次期中考成績?"))
第二次=int(input("請輸入第二次期中考成績?"))
期末考=int(input("請輸入期末考成績?"))

總分為=(第一次+第二次+期末考)
平均為=(第一次+第二次+期末考)/3

print("總分為",總分為,"平均為",平均為)

a=float(input("請輸入幾尺?"))
b=float(input("請輸入幾吋?"))
公分=(a*12+b)*2.54
print("轉換為",公分,"公分")

a=int(input("請輸入座號?"))
組別為=a//5+1
print("組別為",組別為)



