# -*- coding: utf-8 -*-
"""Week3-A108260050-施振宇.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XIC0Sew5fqWfvS0qZYR3urGSjEEKPvzb
"""

print("Hello World")