# -*- coding: utf-8 -*-
"""Week3-Group8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12IMwEi1mhUdVJ8q4HmlVqyq1VMJyGiHo
"""

print("我是廷廷")

print("我是施振宇")

print("我是賴威宇")

print("ooooooooooooooooooof")