# -*- coding: utf-8 -*-
"""Week4-A108260050-施振宇-ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-In6L3QbntxLJ1gLMmpz8motdbUAE8Q9
"""

print"(a)"

a=1
a

a="python"
a

print(a,id(a))

x=1
y=x
print(id(x))

print(y)

0.1+0.1+0.1

bool(0)

bool(1)

a=123
b=123,456
c="Python"

print(a)
print("a=",a)

print(a,end="")

print("Bigflower \n Francis")

print("Bigflower \t Francis")

a=input("Enter Your Number:")

a+1

a=int(input("Enter Your Number:"))

a+1

x=[1,2,3]
y=[1,2.3]
print(x is y)

x=1
y=[1,2,3]
print(x not in y)



